// Centralized API endpoints scoped to parent and student portal use-cases.
export const PARENT_STUDENT_ENDPOINTS = {
  auth: {
    login: "/auth/login/",
    me: "/auth/me/",
    logout: "/auth/logout/",
    register: "/auth/register/",
    refreshToken: "/auth/token/refresh/",
  },
  dashboard: {
    overview: "/dashboard/overview/",
    attendance: "/dashboard/attendance/",
    exams: "/dashboard/exams/",
    finance: "/dashboard/finance/",
    students: "/dashboard/students/",
  },
  students: {
    list: "/students/",
    detail: (id) => `/students/${id}/`,
    enrollments: "/students/enrollments/",
    enrollmentDetail: (id) => `/students/enrollments/${id}/`,
    enrollmentByStream: (streamId) => `/students/enrollments/by-stream/${streamId}/`,
    enrollmentByYear: (yearId) => `/students/enrollments/by-year/${yearId}/`,
    classList: "/students/enrollments/class_list/",
    guardians: "/students/guardians/",
    guardianDetail: (id) => `/students/guardians/${id}/`,
    guardianStudents: (id) => `/students/guardians/${id}/students/`,
    studentGuardians: (studentId) => `/students/${studentId}/guardians/`,
  },
  attendance: {
    students: "/attendance/students/",
    studentDetail: (id) => `/attendance/students/${id}/`,
    bulk: "/attendance/students/bulk/",
    byDate: (date) => `/attendance/students/by-date/${date}/`,
    byStream: (streamId) => `/attendance/students/by-stream/${streamId}/`,
    summary: "/attendance/students/summary/",
  },
  exams: {
    marks: "/exams/marks/",
    marksByExam: (examId) => `/exams/marks/by-exam/${examId}/`,
    subjectGrades: "/exams/subject-grades/",
    termResults: "/exams/term-results/",
    termResultDetail: (id) => `/exams/term-results/${id}/`,
    termResultsByStream: "/exams/term-results/by-stream/",
    reportCards: "/exams/report-cards/",
    annualResults: "/exams/annual-results/",
  },
  reports: {
    reportCard: (enrollmentId, termId) => `/reports/report-card/${enrollmentId}/${termId}/`,
    bulkReportCards: "/reports/report-cards/bulk/",
  },
  finance: {
    balances: "/finance/balances/",
    balanceDetail: (id) => `/finance/balances/${id}/`,
    balanceStatement: (id) => `/finance/balances/${id}/statement/`,
    balancesByStream: "/finance/balances/by-stream/",
    invoices: "/finance/invoices/",
    invoiceDetail: (id) => `/finance/invoices/${id}/`,
    payments: "/finance/payments/",
    paymentDetail: (id) => `/finance/payments/${id}/`,
    dailyCollection: "/finance/payments/daily_collection/",
  },
  notifications: {
    list: "/notifications/",
    unread: "/notifications/unread/",
    markRead: (id) => `/notifications/${id}/read/`,
    readAll: "/notifications/read-all/",
  },
};