/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppStudentIndexRouteImport } from './routes/_app/student/index'
import { Route as AppParentIndexRouteImport } from './routes/_app/parent/index'
import { Route as AppStudentNotificationsRouteImport } from './routes/_app/student/notifications'
import { Route as AppStudentDetailsRouteImport } from './routes/_app/student/details'
import { Route as AppStudentAttendanceRouteImport } from './routes/_app/student/attendance'
import { Route as AppParentNotificationsRouteImport } from './routes/_app/parent/notifications'
import { Route as AppParentChildrenRouteImport } from './routes/_app/parent/children'
import { Route as AppParentAttendanceRouteImport } from './routes/_app/parent/attendance'
import { Route as AppStudentResultsIndexRouteImport } from './routes/_app/student/results/index'
import { Route as AppStudentResultsTermResultsRouteImport } from './routes/_app/student/results/term-results'
import { Route as AppStudentResultsContinuousAssessmentRouteImport } from './routes/_app/student/results/continuous-assessment'
import { Route as AppParentResultsTermResultsRouteImport } from './routes/_app/parent/results/term-results'
import { Route as AppParentResultsStudentResultCardRouteImport } from './routes/_app/parent/results/student-result-card'
import { Route as AppParentResultsContinuousAssessmentsRouteImport } from './routes/_app/parent/results/continuous-assessments'
import { Route as AppParentFinanceReceiptsRouteImport } from './routes/_app/parent/finance/receipts'
import { Route as AppParentFinanceInvoiceRouteImport } from './routes/_app/parent/finance/invoice'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => AppRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentNotificationsRoute = AppStudentNotificationsRouteImport.update({
  id: '/student/notifications',
  path: '/student/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentDetailsRoute = AppStudentDetailsRouteImport.update({
  id: '/student/details',
  path: '/student/details',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentAttendanceRoute = AppStudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppParentNotificationsRoute = AppParentNotificationsRouteImport.update({
  id: '/parent/notifications',
  path: '/parent/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppParentChildrenRoute = AppParentChildrenRouteImport.update({
  id: '/parent/children',
  path: '/parent/children',
  getParentRoute: () => AppRoute,
} as any)
const AppParentAttendanceRoute = AppParentAttendanceRouteImport.update({
  id: '/parent/attendance',
  path: '/parent/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentResultsIndexRoute = AppStudentResultsIndexRouteImport.update({
  id: '/student/results/',
  path: '/student/results/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentResultsTermResultsRoute =
  AppStudentResultsTermResultsRouteImport.update({
    id: '/student/results/term-results',
    path: '/student/results/term-results',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentResultsContinuousAssessmentRoute =
  AppStudentResultsContinuousAssessmentRouteImport.update({
    id: '/student/results/continuous-assessment',
    path: '/student/results/continuous-assessment',
    getParentRoute: () => AppRoute,
  } as any)
const AppParentResultsTermResultsRoute =
  AppParentResultsTermResultsRouteImport.update({
    id: '/parent/results/term-results',
    path: '/parent/results/term-results',
    getParentRoute: () => AppRoute,
  } as any)
const AppParentResultsStudentResultCardRoute =
  AppParentResultsStudentResultCardRouteImport.update({
    id: '/parent/results/student-result-card',
    path: '/parent/results/student-result-card',
    getParentRoute: () => AppRoute,
  } as any)
const AppParentResultsContinuousAssessmentsRoute =
  AppParentResultsContinuousAssessmentsRouteImport.update({
    id: '/parent/results/continuous-assessments',
    path: '/parent/results/continuous-assessments',
    getParentRoute: () => AppRoute,
  } as any)
const AppParentFinanceReceiptsRoute =
  AppParentFinanceReceiptsRouteImport.update({
    id: '/parent/finance/receipts',
    path: '/parent/finance/receipts',
    getParentRoute: () => AppRoute,
  } as any)
const AppParentFinanceInvoiceRoute = AppParentFinanceInvoiceRouteImport.update({
  id: '/parent/finance/invoice',
  path: '/parent/finance/invoice',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof AuthLoginRoute
  '/parent/attendance': typeof AppParentAttendanceRoute
  '/parent/children': typeof AppParentChildrenRoute
  '/parent/notifications': typeof AppParentNotificationsRoute
  '/student/attendance': typeof AppStudentAttendanceRoute
  '/student/details': typeof AppStudentDetailsRoute
  '/student/notifications': typeof AppStudentNotificationsRoute
  '/parent/': typeof AppParentIndexRoute
  '/student/': typeof AppStudentIndexRoute
  '/parent/finance/invoice': typeof AppParentFinanceInvoiceRoute
  '/parent/finance/receipts': typeof AppParentFinanceReceiptsRoute
  '/parent/results/continuous-assessments': typeof AppParentResultsContinuousAssessmentsRoute
  '/parent/results/student-result-card': typeof AppParentResultsStudentResultCardRoute
  '/parent/results/term-results': typeof AppParentResultsTermResultsRoute
  '/student/results/continuous-assessment': typeof AppStudentResultsContinuousAssessmentRoute
  '/student/results/term-results': typeof AppStudentResultsTermResultsRoute
  '/student/results/': typeof AppStudentResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof AuthLoginRoute
  '/parent/attendance': typeof AppParentAttendanceRoute
  '/parent/children': typeof AppParentChildrenRoute
  '/parent/notifications': typeof AppParentNotificationsRoute
  '/student/attendance': typeof AppStudentAttendanceRoute
  '/student/details': typeof AppStudentDetailsRoute
  '/student/notifications': typeof AppStudentNotificationsRoute
  '/parent': typeof AppParentIndexRoute
  '/student': typeof AppStudentIndexRoute
  '/parent/finance/invoice': typeof AppParentFinanceInvoiceRoute
  '/parent/finance/receipts': typeof AppParentFinanceReceiptsRoute
  '/parent/results/continuous-assessments': typeof AppParentResultsContinuousAssessmentsRoute
  '/parent/results/student-result-card': typeof AppParentResultsStudentResultCardRoute
  '/parent/results/term-results': typeof AppParentResultsTermResultsRoute
  '/student/results/continuous-assessment': typeof AppStudentResultsContinuousAssessmentRoute
  '/student/results/term-results': typeof AppStudentResultsTermResultsRoute
  '/student/results': typeof AppStudentResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/parent/attendance': typeof AppParentAttendanceRoute
  '/_app/parent/children': typeof AppParentChildrenRoute
  '/_app/parent/notifications': typeof AppParentNotificationsRoute
  '/_app/student/attendance': typeof AppStudentAttendanceRoute
  '/_app/student/details': typeof AppStudentDetailsRoute
  '/_app/student/notifications': typeof AppStudentNotificationsRoute
  '/_app/parent/': typeof AppParentIndexRoute
  '/_app/student/': typeof AppStudentIndexRoute
  '/_app/parent/finance/invoice': typeof AppParentFinanceInvoiceRoute
  '/_app/parent/finance/receipts': typeof AppParentFinanceReceiptsRoute
  '/_app/parent/results/continuous-assessments': typeof AppParentResultsContinuousAssessmentsRoute
  '/_app/parent/results/student-result-card': typeof AppParentResultsStudentResultCardRoute
  '/_app/parent/results/term-results': typeof AppParentResultsTermResultsRoute
  '/_app/student/results/continuous-assessment': typeof AppStudentResultsContinuousAssessmentRoute
  '/_app/student/results/term-results': typeof AppStudentResultsTermResultsRoute
  '/_app/student/results/': typeof AppStudentResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/parent/attendance'
    | '/parent/children'
    | '/parent/notifications'
    | '/student/attendance'
    | '/student/details'
    | '/student/notifications'
    | '/parent/'
    | '/student/'
    | '/parent/finance/invoice'
    | '/parent/finance/receipts'
    | '/parent/results/continuous-assessments'
    | '/parent/results/student-result-card'
    | '/parent/results/term-results'
    | '/student/results/continuous-assessment'
    | '/student/results/term-results'
    | '/student/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/parent/attendance'
    | '/parent/children'
    | '/parent/notifications'
    | '/student/attendance'
    | '/student/details'
    | '/student/notifications'
    | '/parent'
    | '/student'
    | '/parent/finance/invoice'
    | '/parent/finance/receipts'
    | '/parent/results/continuous-assessments'
    | '/parent/results/student-result-card'
    | '/parent/results/term-results'
    | '/student/results/continuous-assessment'
    | '/student/results/term-results'
    | '/student/results'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/forbidden'
    | '/_auth/login'
    | '/_app/parent/attendance'
    | '/_app/parent/children'
    | '/_app/parent/notifications'
    | '/_app/student/attendance'
    | '/_app/student/details'
    | '/_app/student/notifications'
    | '/_app/parent/'
    | '/_app/student/'
    | '/_app/parent/finance/invoice'
    | '/_app/parent/finance/receipts'
    | '/_app/parent/results/continuous-assessments'
    | '/_app/parent/results/student-result-card'
    | '/_app/parent/results/term-results'
    | '/_app/student/results/continuous-assessment'
    | '/_app/student/results/term-results'
    | '/_app/student/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/student/': {
      id: '/_app/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/': {
      id: '/_app/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/notifications': {
      id: '/_app/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof AppStudentNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/details': {
      id: '/_app/student/details'
      path: '/student/details'
      fullPath: '/student/details'
      preLoaderRoute: typeof AppStudentDetailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/attendance': {
      id: '/_app/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof AppStudentAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/notifications': {
      id: '/_app/parent/notifications'
      path: '/parent/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof AppParentNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/children': {
      id: '/_app/parent/children'
      path: '/parent/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof AppParentChildrenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/attendance': {
      id: '/_app/parent/attendance'
      path: '/parent/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof AppParentAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/results/': {
      id: '/_app/student/results/'
      path: '/student/results'
      fullPath: '/student/results/'
      preLoaderRoute: typeof AppStudentResultsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/results/term-results': {
      id: '/_app/student/results/term-results'
      path: '/student/results/term-results'
      fullPath: '/student/results/term-results'
      preLoaderRoute: typeof AppStudentResultsTermResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/results/continuous-assessment': {
      id: '/_app/student/results/continuous-assessment'
      path: '/student/results/continuous-assessment'
      fullPath: '/student/results/continuous-assessment'
      preLoaderRoute: typeof AppStudentResultsContinuousAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/results/term-results': {
      id: '/_app/parent/results/term-results'
      path: '/parent/results/term-results'
      fullPath: '/parent/results/term-results'
      preLoaderRoute: typeof AppParentResultsTermResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/results/student-result-card': {
      id: '/_app/parent/results/student-result-card'
      path: '/parent/results/student-result-card'
      fullPath: '/parent/results/student-result-card'
      preLoaderRoute: typeof AppParentResultsStudentResultCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/results/continuous-assessments': {
      id: '/_app/parent/results/continuous-assessments'
      path: '/parent/results/continuous-assessments'
      fullPath: '/parent/results/continuous-assessments'
      preLoaderRoute: typeof AppParentResultsContinuousAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/finance/receipts': {
      id: '/_app/parent/finance/receipts'
      path: '/parent/finance/receipts'
      fullPath: '/parent/finance/receipts'
      preLoaderRoute: typeof AppParentFinanceReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/finance/invoice': {
      id: '/_app/parent/finance/invoice'
      path: '/parent/finance/invoice'
      fullPath: '/parent/finance/invoice'
      preLoaderRoute: typeof AppParentFinanceInvoiceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppParentAttendanceRoute: typeof AppParentAttendanceRoute
  AppParentChildrenRoute: typeof AppParentChildrenRoute
  AppParentNotificationsRoute: typeof AppParentNotificationsRoute
  AppStudentAttendanceRoute: typeof AppStudentAttendanceRoute
  AppStudentDetailsRoute: typeof AppStudentDetailsRoute
  AppStudentNotificationsRoute: typeof AppStudentNotificationsRoute
  AppParentIndexRoute: typeof AppParentIndexRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppParentFinanceInvoiceRoute: typeof AppParentFinanceInvoiceRoute
  AppParentFinanceReceiptsRoute: typeof AppParentFinanceReceiptsRoute
  AppParentResultsContinuousAssessmentsRoute: typeof AppParentResultsContinuousAssessmentsRoute
  AppParentResultsStudentResultCardRoute: typeof AppParentResultsStudentResultCardRoute
  AppParentResultsTermResultsRoute: typeof AppParentResultsTermResultsRoute
  AppStudentResultsContinuousAssessmentRoute: typeof AppStudentResultsContinuousAssessmentRoute
  AppStudentResultsTermResultsRoute: typeof AppStudentResultsTermResultsRoute
  AppStudentResultsIndexRoute: typeof AppStudentResultsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppParentAttendanceRoute: AppParentAttendanceRoute,
  AppParentChildrenRoute: AppParentChildrenRoute,
  AppParentNotificationsRoute: AppParentNotificationsRoute,
  AppStudentAttendanceRoute: AppStudentAttendanceRoute,
  AppStudentDetailsRoute: AppStudentDetailsRoute,
  AppStudentNotificationsRoute: AppStudentNotificationsRoute,
  AppParentIndexRoute: AppParentIndexRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppParentFinanceInvoiceRoute: AppParentFinanceInvoiceRoute,
  AppParentFinanceReceiptsRoute: AppParentFinanceReceiptsRoute,
  AppParentResultsContinuousAssessmentsRoute:
    AppParentResultsContinuousAssessmentsRoute,
  AppParentResultsStudentResultCardRoute:
    AppParentResultsStudentResultCardRoute,
  AppParentResultsTermResultsRoute: AppParentResultsTermResultsRoute,
  AppStudentResultsContinuousAssessmentRoute:
    AppStudentResultsContinuousAssessmentRoute,
  AppStudentResultsTermResultsRoute: AppStudentResultsTermResultsRoute,
  AppStudentResultsIndexRoute: AppStudentResultsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
